" Some file types should wrap their text
function! s:setUpMarkdown()
  setlocal wrap
  setlocal linebreak
  setlocal textwidth=80
  setlocal nolist
  setlocal spell
endfunction


""
"" Basic setup
""
set nocompatible                  " Use vim, no vi defaults
set number                        " Show line numbers
set ruler                         " Show line and column number
set encoding=utf-8
set spelllang=en_gb
set guifont=Monaco:h12
set backupdir^=~/.vim/_backup//   " Where to put backup files.
set directory^=~/.vim/_temp//     " Where to put swap files.


""
"" Colors
""
syntax enable
filetype plugin indent on
color obsidian2
set background=light  " Overrides obsidian2


""
"" Indentation
""
set wrap
set expandtab                   " Use spaces, not tabs
set tabstop=2                   " A tab is two spaces
set shiftwidth=2                " An autoindent (with <<) is two spaces
set list                        " Show invisible characters
set backspace=indent,eol,start  " Backspace through everything in insert mode


""
"" Searching
""
set hlsearch    " Highlight matches
set incsearch   " Incremental searching
set ignorecase  " Searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

" Toggle hlsearch with <leader>hs
nmap <leader>hs :set hlsearch! hlsearch?<CR>


""
"" listchars
""
set listchars=""            " Reset the listchars
set listchars=tab:\ \       " A tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.      " Show trailing spaces as dots
set listchars+=extends:>    " The character to show when wrap is off and the line continues beyond the right
set listchars+=precedes:<   " The character to show when wrap is off and the line continues beyond the left


""
"" wildignore
""
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*
set wildignore+=*.swp,*~,._*


""
"" autocmd
""
if has("autocmd")
  " In Makefiles, use real tabs, not tabs expanded to spaces
  au FileType make setlocal noexpandtab

  " Make sure all Markdown files have the correct filetype set and setup wrapping
  au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} set filetype=markdown
  au FileType markdown call s:setUpMarkdown()

  " Spell-check Git messages
  au FileType gitcommit setlocal spell

  " Treat JSON files like JavaScript
  au BufNewFile,BufRead *.json setlocal filetype=javascript

  " make Python follow PEP8 for whitespace ( http://www.python.org/dev/peps/pep-0008/ )
  au FileType python setlocal softtabstop=4 tabstop=4 shiftwidth=4

  " Use tabs instead of spaces in PHP
  au FileType php setlocal tabstop=2 noexpandtab

  " Remember last location in file, but not for commit messages.
  au BufReadPost * if &filetype !~ '^git\c' && line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g`\"" | endif
endif


""
"" statusline
""
if has("statusline") && !&cp
  set laststatus=2  " Always show the status bar

  set statusline=%t
  set statusline+=\ Line:\ %l/%L
  set statusline+=\ Column:\ %v
  set statusline+=%=
  set statusline+=%y\ [%{''.(&fenc!=''?&fenc:&enc).''}]%(\ %M%R%)\ Buffer\ #%n
endif

